export interface UnitMetadata {
  landlordEntity: string;
  referenceCode: string;
  bankName: string;
  sortCode: string;
  accountNumber: string;
  accountName: string;
  epcRating: string;
  epcScore: number;
  epcCertificate: string;
  epcAssessedDate: string;
  epcExpiryDate: string;
  epcAssessor: string;
  eicSerial: string;
  eicInspectedDate: string;
  eicExpiryDate: string;
  insurancePolicy: string;
  insuranceStartDate: string;
  insuranceStatus: string;
  elecMeterSerial: string;
  elecMeterCheckInValue: string;
  elecMeterCheckInDate: string;
  waterMeterSerial: string;
  waterMeterCheckInValue: string;
  waterMeterCheckInDate: string;
  outstandingDocs: string[];
  complianceNotes: string;
}

export const tenantDataMap: Record<string, UnitMetadata> = {
  A01: {
    landlordEntity: "Hemnani Estates SPV1",
    referenceCode: "ASHFORD-01",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "C",
    epcScore: 74,
    epcCertificate: "9057-7907-4762-8798-8302",
    epcAssessedDate: "10 August 2023",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27527814",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195089",
    elecMeterCheckInValue: "11,967 kWh",
    elecMeterCheckInDate: "29 April 2026",
    waterMeterSerial: "23LU028300",
    waterMeterCheckInValue: "94 m³",
    waterMeterCheckInDate: "29 April 2026",
    outstandingDocs: [],
    complianceNotes: "tv to be removed",
  },
  A02: {
    landlordEntity: "Hemnani Estates SPV1",
    referenceCode: "ASHFORD-02",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "C",
    epcScore: 77,
    epcCertificate: "7237-9038-4700-0905-8292",
    epcAssessedDate: "15 August 2023",
    epcExpiryDate: "14 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27527815",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195090",
    elecMeterCheckInValue: "14,682 kWh",
    elecMeterCheckInDate: "25 October 2025",
    waterMeterSerial: "23LU028301",
    waterMeterCheckInValue: "112 m³",
    waterMeterCheckInDate: "25 October 2025",
    outstandingDocs: ["Signed Check-in Inventory"],
    complianceNotes: "Awaiting tenant signature on inventory.",
  },
  A03: {
    landlordEntity: "Hemnani Estates SPV1",
    referenceCode: "ASHFORD-03",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "C",
    epcScore: 75,
    epcCertificate: "9057-7907-4762-8798-8303",
    epcAssessedDate: "10 August 2023",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27527816",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195091",
    elecMeterCheckInValue: "8,912 kWh",
    elecMeterCheckInDate: "29 March 2025",
    waterMeterSerial: "23LU028302",
    waterMeterCheckInValue: "76 m³",
    waterMeterCheckInDate: "29 March 2025",
    outstandingDocs: ["Landlord Indemnity Signed Copy"],
    complianceNotes: "Indemnity agreement to be counter-signed by landlord.",
  },
  A04: {
    landlordEntity: "Hemnani Estates SPV1",
    referenceCode: "ASHFORD-04",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "C",
    epcScore: 76,
    epcCertificate: "9057-7907-4762-8798-8304",
    epcAssessedDate: "10 August 2023",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27527817",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195092",
    elecMeterCheckInValue: "9,430 kWh",
    elecMeterCheckInDate: "28 February 2026",
    waterMeterSerial: "23LU028303",
    waterMeterCheckInValue: "83 m³",
    waterMeterCheckInDate: "28 February 2026",
    outstandingDocs: ["Electrical EIC Certificate (Arthur Upload)", "Signed Check-in Inventory"],
    complianceNotes: "EIC certificate needs to be formally attached on Arthur Online.",
  },
  A05: {
    landlordEntity: "Hemnani Estates SPV3",
    referenceCode: "ASHFORD-05",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "C",
    epcScore: 74,
    epcCertificate: "9057-7907-4762-8798-8305",
    epcAssessedDate: "10 August 2023",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27527818",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195093",
    elecMeterCheckInValue: "10,214 kWh",
    elecMeterCheckInDate: "14 September 2024",
    waterMeterSerial: "23LU028304",
    waterMeterCheckInValue: "89 m³",
    waterMeterCheckInDate: "14 September 2024",
    outstandingDocs: ["Landlord Terms of Business (TOB) Signed Copy"],
    complianceNotes: "Awaiting landlord counter-signature on Terms of Business.",
  },
  A06: {
    landlordEntity: "Hemnani Estates SPV3",
    referenceCode: "ASHFORD-06",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "C",
    epcScore: 75,
    epcCertificate: "9057-7907-4762-8798-8306",
    epcAssessedDate: "10 August 2023",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27527819",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195088",
    elecMeterCheckInValue: "8,938 kWh",
    elecMeterCheckInDate: "5 December 2025",
    waterMeterSerial: "23LU028272",
    waterMeterCheckInValue: "108 m³",
    waterMeterCheckInDate: "5 December 2025",
    outstandingDocs: ["Deposit protection certificate / prescribed information", "EPC", "EICR / electrical certificate"],
    complianceNotes: "Bathroom/WC skirting RHS has water damage.",
  },
  A07: {
    landlordEntity: "Hemnani Estates Limited & IQRA Asset Management Limited",
    referenceCode: "ASHFORD-07",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "C",
    epcScore: 73,
    epcCertificate: "0021-9882-2649-0707-6760",
    epcAssessedDate: "29 August 2025",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27528112",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195073",
    elecMeterCheckInValue: "6,873 kWh",
    elecMeterCheckInDate: "29 August 2025",
    waterMeterSerial: "23LU23485",
    waterMeterCheckInValue: "86 m³",
    waterMeterCheckInDate: "29 August 2025",
    outstandingDocs: ["Deposit protection certificate / prescribed information", "Tenant mobile & email details", "Guarantor details"],
    complianceNotes: "Shower Room flaking paint within cubicle. Marks to basin waste. Cream rug stained. Staining behind hob.",
  },
  A08: {
    landlordEntity: "Hemnani Estates Limited & IQRA Asset Management Limited",
    referenceCode: "ASHFORD-08",
    bankName: "Habib Bank",
    sortCode: "04-29-09",
    accountNumber: "95772170",
    accountName: "IQRA Asset Management",
    epcRating: "C",
    epcScore: 76,
    epcCertificate: "0072-2877-7152-9898-1601",
    epcAssessedDate: "30 November 2024",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27528147",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195146",
    elecMeterCheckInValue: "4,500 kWh",
    elecMeterCheckInDate: "29 November 2024",
    waterMeterSerial: "23LU28298",
    waterMeterCheckInValue: "90 m³",
    waterMeterCheckInDate: "29 November 2024",
    outstandingDocs: ["Deposit protection certificate / prescribed information", "Tenant mobile & email details"],
    complianceNotes: "Guarantor agreement in place.",
  },
  A09: {
    landlordEntity: "Hemnani Estates Limited & IQRA Asset Management Limited",
    referenceCode: "ASHFORD-09",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "C",
    epcScore: 76,
    epcCertificate: "2278-4018-0875-5105-0192",
    epcAssessedDate: "2 January 2026",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27528184",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195140",
    elecMeterCheckInValue: "8,216 kWh",
    elecMeterCheckInDate: "2 January 2026",
    waterMeterSerial: "23LU028255",
    waterMeterCheckInValue: "195 m³",
    waterMeterCheckInDate: "2 January 2026",
    outstandingDocs: ["Deposit protection certificate / prescribed information", "Tenant mobile & email details"],
    complianceNotes: "Liquid staining on shower room LHS wall. Water damage to skirting either side of cubicle. Bedroom wall-mounted heater loose hinge.",
  },
  A10: {
    landlordEntity: "Hemnani Estates Limited & IQRA Asset Management Limited",
    referenceCode: "ASHFORD-10",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "C",
    epcScore: 75,
    epcCertificate: "9057-7907-4762-8798-8310",
    epcAssessedDate: "10 August 2023",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27528210",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195210",
    elecMeterCheckInValue: "10,000 kWh",
    elecMeterCheckInDate: "25 September 2025",
    waterMeterSerial: "23LU028210",
    waterMeterCheckInValue: "50 m³",
    waterMeterCheckInDate: "25 September 2025",
    outstandingDocs: ["Deposit protection certificate / prescribed information"],
    complianceNotes: "Property parameters pending full verification.",
  },
  A11: {
    landlordEntity: "Hemnani Estates Limited & IQRA Asset Management Limited",
    referenceCode: "ASHFORD-11",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "B",
    epcScore: 81,
    epcCertificate: "7067-4447-2512-1098-9506",
    epcAssessedDate: "10 October 2024",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27528236",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195236",
    elecMeterCheckInValue: "9,500 kWh",
    elecMeterCheckInDate: "10 October 2024",
    waterMeterSerial: "23LU028236",
    waterMeterCheckInValue: "150 m³",
    waterMeterCheckInDate: "10 October 2024",
    outstandingDocs: ["Deposit protection certificate / prescribed information"],
    complianceNotes: "Sprinkler system active in apartment.",
  },
  A12: {
    landlordEntity: "Heywood Capital Partners Limited",
    referenceCode: "ASHFORD-12",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "C",
    epcScore: 73,
    epcCertificate: "2479-4538-0677-1704-0598",
    epcAssessedDate: "10 August 2023",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27528270",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195157",
    elecMeterCheckInValue: "05,003 kWh",
    elecMeterCheckInDate: "13 April 2025",
    waterMeterSerial: "23LU028301",
    waterMeterCheckInValue: "51 m³",
    waterMeterCheckInDate: "13 April 2025",
    outstandingDocs: ["Signed Tenancy Agreement", "Landlord Indemnity", "Terms of Business", "Deposit protection certificate"],
    complianceNotes: "Entrance hall lighting — one spotlight not working. Door entry phone untested. Extractor fan dusty.",
  },
  A13: {
    landlordEntity: "HEMNANI ESTATES (SPV1) 2-19 ASHFORD YARD BN21 LIMITED / IQRA Asset Management Limited",
    referenceCode: "ASHFORD-13",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "C",
    epcScore: 73,
    epcCertificate: "8083-9357-0402-0798-3509",
    epcAssessedDate: "10 August 2023",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27528311",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195101",
    elecMeterCheckInValue: "163,164 kWh",
    elecMeterCheckInDate: "28 October 2024",
    waterMeterSerial: "23-0056424",
    waterMeterCheckInValue: "00,031 m³",
    waterMeterCheckInDate: "28 October 2024",
    outstandingDocs: ["Deposit protection certificate / proof", "Tenant email addresses", "Guarantor contact details", "EICR confirmation"],
    complianceNotes: "Failed tenant references accepted with guarantors Ashley Veness and Kevin Saunders. Deposit not held by Sequence.",
  },
  A14: {
    landlordEntity: "Hemnani Estates Limited & IQRA Asset Management Limited",
    referenceCode: "ASHFORD-14",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "C",
    epcScore: 76,
    epcCertificate: "2351-9908-9978-7501-0395",
    epcAssessedDate: "10 August 2023",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27485103",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195097",
    elecMeterCheckInValue: "10,156 kWh",
    elecMeterCheckInDate: "03 March 2026",
    waterMeterSerial: "23LU240793",
    waterMeterCheckInValue: "156 m³",
    waterMeterCheckInDate: "03 March 2026",
    outstandingDocs: ["Deposit protection certificate / proof", "Tenant email address", "EICR confirmation"],
    complianceNotes: "Heavy mould in sealant around shower cubicle tray. Grout discolouration. Water damage to skirting RHS of shower cubicle.",
  },
  A15: {
    landlordEntity: "Hemnani Estates Limited & IQRA Asset Management Limited",
    referenceCode: "ASHFORD-15",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "C",
    epcScore: 73,
    epcCertificate: "9010-2807-6232-6298-3107",
    epcAssessedDate: "10 August 2023",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27485182",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195096",
    elecMeterCheckInValue: "09,828 kWh",
    elecMeterCheckInDate: "23 February 2026",
    waterMeterSerial: "23LU240790",
    waterMeterCheckInValue: "85 m³",
    waterMeterCheckInDate: "23 February 2026",
    outstandingDocs: ["Deposit protection certificate / proof", "Tenant email address", "Guarantor agreement/details", "EICR confirmation"],
    complianceNotes: "Seal within shower cubicle discoloured. Marks/damage to skirting to side of shower. 3 wall lights in kitchen/lounge not working.",
  },
  A16: {
    landlordEntity: "Hemnani Estates Limited & IQRA Asset Management Limited",
    referenceCode: "ASHFORD-16",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "B",
    epcScore: 81,
    epcCertificate: "5623-9483-2470-0305-5722",
    epcAssessedDate: "10 August 2023",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: "27484901",
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "22E5195292",
    elecMeterCheckInValue: "05,346 kWh",
    elecMeterCheckInDate: "30 December 2025",
    waterMeterSerial: "23LU023487",
    waterMeterCheckInValue: "80 m³",
    waterMeterCheckInDate: "30 December 2025",
    outstandingDocs: ["Signed tenancy agreement (TA is unsigned)", "Deposit protection certificate", "Tenant email address", "EICR confirmation"],
    complianceNotes: "Door entry phone untested. Swelling to bottom of bedroom/shower door. Water damage to skirting RHS of shower cubicle.",
  },
  J06: {
    landlordEntity: "Hemnani Estates (SPV3) Limited",
    referenceCode: "JEVINGTON-06",
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70027233",
    accountName: "Dinesh Hemnani",
    epcRating: "D",
    epcScore: 62,
    epcCertificate: "0300-2520-5020-2695-0971",
    epcAssessedDate: "10 February 2025",
    epcExpiryDate: "21 April 2035",
    epcAssessor: "Jeffrey Downton (Elmhurst, ID EES/026599)",
    eicSerial: "30825833",
    eicInspectedDate: "03 January 2025",
    eicExpiryDate: "January 2035",
    insurancePolicy: "Ageas Commercial Block Insurance",
    insuranceStartDate: "01 May 2025",
    insuranceStatus: "Active",
    elecMeterSerial: "Z11QF38495",
    elecMeterCheckInValue: "13,645 kWh",
    elecMeterCheckInDate: "27 May 2025",
    waterMeterSerial: "N/A",
    waterMeterCheckInValue: "N/A",
    waterMeterCheckInDate: "27 May 2025",
    outstandingDocs: ["Deposit protection certificate / prescribed information", "Guarantor reference reports", "Right to Rent checks"],
    complianceNotes: "Entrance hall coat hooks not fitted. Laminate flooring has smear marks and light dust.",
  },
};

// Fallback metadata generator for other units to keep dashboard functional
export function getUnitMetadata(unitName: string): UnitMetadata {
  const match = tenantDataMap[unitName];
  if (match) return match;

  // Extract digits for sequential codes (e.g., A07 -> ASHFORD-07)
  const unitNum = unitName.replace(/^\D+/g, "") || "01";
  const formattedNum = unitNum.padStart(2, "0");

  return {
    landlordEntity: "Hemnani Estates SPV1",
    referenceCode: `ASHFORD-${formattedNum}`,
    bankName: "Habib Bank",
    sortCode: "60-95-11",
    accountNumber: "70028947",
    accountName: "Hemnani Estates",
    epcRating: "C",
    epcScore: 75,
    epcCertificate: `9057-7907-4762-8798-83${formattedNum}`,
    epcAssessedDate: "10 August 2023",
    epcExpiryDate: "9 August 2033",
    epcAssessor: "Carl Taylor (Quidos, ID QUID205985)",
    eicSerial: `275278${formattedNum}`,
    eicInspectedDate: "21 June 2023",
    eicExpiryDate: "June 2028",
    insurancePolicy: "Ageas 'HomeGuard Let' Building Insurance",
    insuranceStartDate: "15 April 2025",
    insuranceStatus: "Active",
    elecMeterSerial: `22E5195${formattedNum}`,
    elecMeterCheckInValue: "10,000 kWh",
    elecMeterCheckInDate: "01 January 2026",
    waterMeterSerial: `23LU0283${formattedNum}`,
    waterMeterCheckInValue: "50 m³",
    waterMeterCheckInDate: "01 January 2026",
    outstandingDocs: ["Awaiting Full Compliance Sync"],
    complianceNotes: "Property parameters pending full verification.",
  };
}
