import { PrismaClient } from "../generated/prisma";

const prisma = new PrismaClient();

async function main() {
  const adminEmail = "admin@heywood.com";
  const adminPassword = "admin123";

  const admin = await prisma.user.upsert({
    where: { email: adminEmail },
    update: {
      password: adminPassword,
      role: "admin",
      name: "Admin User",
    },
    create: {
      email: adminEmail,
      password: adminPassword,
      role: "admin",
      name: "Admin User",
    },
  });

  console.log("Admin credential seeded successfully into PostgreSQL!");
  console.log("Email:", admin.email);
  console.log("Password:", admin.password);

  // Seed Mock Token
  const expiresAt = new Date(Date.now() + 3600 * 1000 * 24 * 365); // 1 year
  await prisma.arthurToken.upsert({
    where: { id: "singleton" },
    update: {
      accessToken: "mock_access_token",
      refreshToken: "mock_refresh_token",
      expiresAt,
    },
    create: {
      id: "singleton",
      accessToken: "mock_access_token",
      refreshToken: "mock_refresh_token",
      expiresAt,
    },
  });
  console.log("Arthur Mock Token seeded successfully!");

  // Seed Properties
  const properties = [
    { id: "101", name: "Ashford Yard", address: "145a Ashford Road, Eastbourne, East Sussex" },
    { id: "102", name: "Jevington Yard Block J", address: "Jevington Rd, Eastbourne" },
    { id: "103", name: "Longstone Yard Block L", address: "Longstone Rd, Eastbourne" },
  ];

  for (const prop of properties) {
    await prisma.arthurProperty.upsert({
      where: { id: prop.id },
      update: prop,
      create: prop,
    });
  }
  console.log("Arthur Properties seeded successfully!");

  // Seed Units
  const units = [
    { id: "201", propertyId: "101", name: "A01", status: "Occupied" },
    { id: "202", propertyId: "101", name: "A02", status: "Occupied" },
    { id: "203", propertyId: "101", name: "A03", status: "Occupied" },
    { id: "207", propertyId: "101", name: "A04", status: "Occupied" },
    { id: "208", propertyId: "101", name: "A05", status: "Occupied" },
    { id: "209", propertyId: "101", name: "A06", status: "Occupied" },
    { id: "210", propertyId: "101", name: "A07", status: "Occupied" },
    { id: "211", propertyId: "101", name: "A08", status: "Occupied" },
    { id: "212", propertyId: "101", name: "A09", status: "Occupied" },
    { id: "213", propertyId: "101", name: "A11", status: "Occupied" },
    { id: "215", propertyId: "101", name: "A12", status: "Vacant" },
    { id: "216", propertyId: "101", name: "A13", status: "Occupied" },
    { id: "217", propertyId: "101", name: "A14", status: "Occupied" },
    { id: "218", propertyId: "101", name: "A15", status: "Occupied" },
    { id: "219", propertyId: "101", name: "A16", status: "Occupied" },
    { id: "204", propertyId: "102", name: "J01", status: "Occupied" },
    { id: "205", propertyId: "102", name: "J02", status: "Occupied" },
    { id: "214", propertyId: "102", name: "J06", status: "Occupied" },
    { id: "206", propertyId: "103", name: "L01", status: "Occupied" },
  ];

  for (const unit of units) {
    await prisma.arthurUnit.upsert({
      where: { id: unit.id },
      update: unit,
      create: unit,
    });
  }
  console.log("Arthur Units seeded successfully!");

  // Seed Tenancies
  const tenancies = [
    {
      id: "301",
      unitId: "201",
      status: "Occupied",
      startDate: "2025-04-30",
      endDate: "2026-04-29",
      rent: "£ 1,150.00",
      rentVal: 1150.0,
      deposit: "£ 1,325.00",
      depositVal: 1325.0,
      lodged: "TBC",
      received: "Received",
      tenants: ["Verghese Kurien", "Neha Zacharias"],
      phone: [],
      email: ["neha.zacharias@email.com"],
      lettingType: "AST ROLLING",
      rentStatus: "Paid up to date",
      commentary: "Gated courtyard development, 18 apartments + 2 houses. Two-storey mews house. Rent is due on the 29th of each month by standing order.",
      code: "A01-KEY",
    },
    {
      id: "302",
      unitId: "202",
      status: "Occupied",
      startDate: "2025-10-25",
      endDate: "2026-10-24",
      rent: "£ 1,150.00",
      rentVal: 1150.0,
      deposit: "£ 1,325.00",
      depositVal: 1325.0,
      lodged: "TBC",
      received: "Received",
      tenants: ["Akshaya Rajagopal"],
      phone: ["07943550828"],
      email: ["akshayaraj25@yahoo.com"],
      lettingType: "FIXED TERM",
      rentStatus: "Paid up to date",
      commentary: "Tenant swap complete. Inventory needs checking.",
      code: "",
    },
    {
      id: "303",
      unitId: "203",
      status: "Occupied",
      startDate: "2025-03-29",
      endDate: "2026-03-28",
      rent: "£ 1,100.00",
      rentVal: 1100.0,
      deposit: "£ 1,265.00",
      depositVal: 1265.0,
      lodged: "TBC",
      received: "Received",
      tenants: ["Keyss Hussein"],
      phone: ["07922392166"],
      email: ["keyss.alcheikh@gmail.com"],
      lettingType: "FIXED TERM",
      rentStatus: "Paid up to date",
      commentary: "Keyss Hussein tenancy.",
      code: "",
    },
    {
      id: "307",
      unitId: "207",
      status: "Occupied",
      startDate: "2026-02-28",
      endDate: "2027-02-27",
      rent: "£ 1,100.00",
      rentVal: 1100.0,
      deposit: "£ 1,265.00",
      depositVal: 1265.0,
      lodged: "TBC",
      received: "Received",
      tenants: ["Hikmot Adeola Mustapha", "Saheed Olawale Lawal"],
      phone: ["07928223989", "07576323623"],
      email: ["hikmotmustapha@gmail.com", "lawalolw@gmail.com"],
      lettingType: "FIXED TERM",
      rentStatus: "Paid up to date",
      commentary: "Flat 4 tenancy.",
      code: "",
    },
    {
      id: "308",
      unitId: "208",
      status: "Occupied",
      startDate: "2024-09-14",
      endDate: "rolling",
      rent: "£ 1,100.00",
      rentVal: 1100.0,
      deposit: "£ 1,265.00",
      depositVal: 1265.0,
      lodged: "11/11/2024",
      received: "Received",
      tenants: ["Oliver Berry", "Ellie-Mae Meredith"],
      phone: ["07479 108 080"],
      email: ["Oliverjbarry23@gmail.com", "Elliemae210104@icloud.com"],
      lettingType: "AST ROLLING",
      rentStatus: "Paid up to date",
      commentary: "Oliver Berry & Ellie-Mae Meredith tenancy.",
      code: "",
    },
    {
      id: "309",
      unitId: "209",
      status: "Occupied",
      startDate: "2025-12-05",
      endDate: "2026-12-04",
      rent: "£ 1,150.00",
      rentVal: 1150.0,
      deposit: "£ 1,325.00",
      depositVal: 1325.0,
      lodged: "TBC",
      received: "Received",
      tenants: ["Laetitia Stephanie Briquet"],
      phone: ["7403322421"],
      email: ["l.briquet@live.fr"],
      lettingType: "FIXED TERM",
      rentStatus: "Paid up to date",
      commentary: "Laetitia Stephanie Briquet tenancy. Bathroom/WC skirting RHS has water damage.",
      code: "",
    },
    {
      id: "310",
      unitId: "210",
      status: "Occupied",
      startDate: "2025-08-30",
      endDate: "2026-08-29",
      rent: "£ 1,150.00",
      rentVal: 1150.0,
      deposit: "£ 1,325.00",
      depositVal: 1325.0,
      lodged: "TBC",
      received: "Received",
      tenants: ["Benjamin Caruana Montaldo"],
      phone: [],
      email: ["benjamin.c@example.com"],
      lettingType: "FIXED TERM",
      rentStatus: "Paid up to date",
      commentary: "Flat 7 Ashford Yard tenancy. Note rent payment reference conflict to 6 Ashford Yard.",
      code: "",
    },
    {
      id: "311",
      unitId: "211",
      status: "Occupied",
      startDate: "2024-11-30",
      endDate: "2025-11-29",
      rent: "£ 1,100.00",
      rentVal: 1100.0,
      deposit: "£ 1,265.00",
      depositVal: 1265.0,
      lodged: "TBC",
      received: "Received",
      tenants: ["Maureen Feeney"],
      phone: [],
      email: ["maureen.f@example.com"],
      lettingType: "AST ROLLING",
      rentStatus: "Paid up to date",
      commentary: "Flat 8 Ashford Yard. Accept with John Feeney as guarantor.",
      code: "",
    },
    {
      id: "312",
      unitId: "212",
      status: "Occupied",
      startDate: "2026-01-03",
      endDate: "2027-01-02",
      rent: "£ 1,100.00",
      rentVal: 1100.0,
      deposit: "£ 1,265.00",
      depositVal: 1265.0,
      lodged: "TBC",
      received: "Received",
      tenants: ["Wisdom Okechukwu Oturi", "Grace Okechukwu"],
      phone: [],
      email: ["wisdom.o@example.com"],
      lettingType: "FIXED TERM",
      rentStatus: "Paid up to date",
      commentary: "Flat 9 Ashford Yard. Ground floor one-bedroom flat.",
      code: "",
    },
    {
      id: "313",
      unitId: "213",
      status: "Occupied",
      startDate: "2024-10-10",
      endDate: "2025-10-09",
      rent: "£ 1,100.00",
      rentVal: 1100.0,
      deposit: "£ 1,265.00",
      depositVal: 1265.0,
      lodged: "TBC",
      received: "Received",
      tenants: ["Rachel Njogu", "Sheldon Williams"],
      phone: ["07928521149"],
      email: ["rachel.n@example.com"],
      lettingType: "AST ROLLING",
      rentStatus: "Paid up to date",
      commentary: "Flat 11 Ashford Yard. Sprinkler system active.",
      code: "",
    },
    {
      id: "316",
      unitId: "216",
      status: "Occupied",
      startDate: "2024-10-28",
      endDate: "2025-10-27",
      rent: "£ 1,100.00",
      rentVal: 1100.0,
      deposit: "£ 1,265.00",
      depositVal: 1265.0,
      lodged: "TBC",
      received: "Received",
      tenants: ["Lily Mae Veness", "Hayden Riley Saunders"],
      phone: ["07492491388"],
      email: ["lily.v@example.com"],
      lettingType: "AST ROLLING",
      rentStatus: "Paid up to date",
      commentary: "Flat 13 tenancy. Fixed term ended, now periodic.",
      code: "",
    },
    {
      id: "317",
      unitId: "217",
      status: "Occupied",
      startDate: "2026-03-05",
      endDate: "2026-08-04",
      rent: "£ 1,100.00",
      rentVal: 1100.0,
      deposit: "£ 1,265.00",
      depositVal: 1265.0,
      lodged: "TBC",
      received: "Received",
      tenants: ["Darshana Nair"],
      phone: ["07543054172"],
      email: ["darshana.n@example.com"],
      lettingType: "FIXED TERM",
      rentStatus: "Paid up to date",
      commentary: "Flat 14 tenancy. Ground floor one-bedroom apartment.",
      code: "",
    },
    {
      id: "318",
      unitId: "218",
      status: "Occupied",
      startDate: "2026-02-24",
      endDate: "2027-02-23",
      rent: "£ 1,100.00",
      rentVal: 1100.0,
      deposit: "£ 1,265.00",
      depositVal: 1265.0,
      lodged: "TBC",
      received: "Received",
      tenants: ["Samuel Leslie Wies"],
      phone: ["07876743315"],
      email: ["samuel.w@example.com"],
      lettingType: "FIXED TERM",
      rentStatus: "Paid up to date",
      commentary: "Flat 15 tenancy. Failed references accepted with guarantor Katie Louise Astin.",
      code: "",
    },
    {
      id: "319",
      unitId: "219",
      status: "Occupied",
      startDate: "2025-12-31",
      endDate: "2026-12-30",
      rent: "£ 1,100.00",
      rentVal: 1100.0,
      deposit: "£ 1,265.00",
      depositVal: 1265.0,
      lodged: "TBC",
      received: "Received",
      tenants: ["Marina Rodriguez Fernandez"],
      phone: ["+34 660972327"],
      email: ["marina.r@example.com"],
      lettingType: "FIXED TERM",
      rentStatus: "Paid up to date",
      commentary: "Flat 16 tenancy. Unsigned TA.",
      code: "",
    },
    {
      id: "314",
      unitId: "214",
      status: "Occupied",
      startDate: "2025-05-27",
      endDate: "2026-05-26",
      rent: "£ 1,100.00",
      rentVal: 1100.0,
      deposit: "£ 1,265.00",
      depositVal: 1265.0,
      lodged: "TBC",
      received: "Received",
      tenants: ["Shae Julia Peggy Smith", "Reuben Alexander Ure Samms"],
      phone: [],
      email: ["shae.smith@example.com"],
      lettingType: "FIXED TERM",
      rentStatus: "Paid up to date",
      commentary: "Flat 6 Jevington Yard. Payments to Dinesh Hemnani.",
      code: "",
    },
    {
      id: "304",
      unitId: "204",
      status: "Occupied",
      startDate: "2024-06-15",
      endDate: "2025-06-15",
      rent: "£ 950.00",
      rentVal: 950.0,
      deposit: "£ 1,100.00",
      depositVal: 1100.0,
      lodged: "Lodged",
      received: "Received",
      tenants: ["David Miller"],
      phone: ["07456123789"],
      email: ["david.m@example.com"],
      lettingType: "FIXED TERM",
      rentStatus: "Arrears",
      commentary: "Arrears of £950. Sent warning email.",
      code: "",
    },
    {
      id: "305",
      unitId: "205",
      status: "Occupied",
      startDate: "2024-09-01",
      endDate: "2025-09-01",
      rent: "£ 1,100.00",
      rentVal: 1100.0,
      deposit: "£ 1,250.00",
      depositVal: 1250.0,
      lodged: "Lodged",
      received: "Received",
      tenants: ["Sarah Connor"],
      phone: ["07852369147"],
      email: ["sarah.c@example.com"],
      lettingType: "AST ROLLING",
      rentStatus: "Paid up to date",
      commentary: "No issues reported.",
      code: "",
    },
    {
      id: "306",
      unitId: "206",
      status: "Occupied",
      startDate: "2023-12-01",
      endDate: "2024-12-01",
      rent: "£ 1,500.00",
      rentVal: 1500.0,
      deposit: "£ 1,800.00",
      depositVal: 1800.0,
      lodged: "Lodged",
      received: "Received",
      tenants: ["Robert Downey"],
      phone: ["07596847362"],
      email: ["robert.d@example.com"],
      lettingType: "FIXED TERM",
      rentStatus: "Paid up to date",
      commentary: "Renewed agreement for 12 months.",
      code: "",
    },
  ];

  for (const tenancy of tenancies) {
    await prisma.arthurTenancy.upsert({
      where: { id: tenancy.id },
      update: tenancy,
      create: tenancy,
    });
  }
  console.log("Arthur Tenancies seeded successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
